import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Provider from "./components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex justify-evenly">
            <li>
              <Link href="/">Home(SSG)</Link>
            </li>

            <li>
              <Link href="/news">News(ISR)</Link>
            </li>
            <li>
              <Link href="/blogs">Blogs(SSR)</Link>
            </li>
            <li>
              <Link href="/todolist">todoList(CSR)</Link>
            </li>
          </ul>
        </nav>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
